version: "3.8"
services:
  core:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    image: "postgres"
    volumes:
       -  ./postgres-data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - database.dev.env 